import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CustomTitleBar from "../components/custom/controller";
import { cookies } from "next/dist/server/request/cookies";
import {
  SidebarProvider,
  SidebarTrigger,
} from "@/components/animate-ui/components/radix/sidebar";
import { AppSidebar } from "../components/custom/app_sidebar";
import { AnimeMediaProvider } from "@/contexts/anime_context";
import { AuthProvider } from "@/contexts/auth_context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-y-hidden`}
      >
        <AuthProvider>
          <AnimeMediaProvider>
            <SidebarProvider>
              <main>
                <CustomTitleBar />
                <AppSidebar />
                {children}
              </main>
            </SidebarProvider>
          </AnimeMediaProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
